// line 1 of the sample handler module
// line 2 of the sample handler module
// line 3 of the sample handler module
// line 4 of the sample handler module
// line 5 of the sample handler module
// line 6 of the sample handler module
// line 7 of the sample handler module
// line 8 of the sample handler module
// line 9 of the sample handler module
// line 10 of the sample handler module
// line 11 of the sample handler module
// line 12 of the sample handler module
// line 13 of the sample handler module
// line 14 of the sample handler module
// line 15 of the sample handler module
// line 16 of the sample handler module
// line 17 of the sample handler module
// line 18 of the sample handler module
// line 19 of the sample handler module
// line 20 of the sample handler module
function exampleHandler(req, res) {
  // the anchor lives here, right where the issue said it would
  return res.json({ ok: true });
}
// line 25 of the sample handler module
// line 26 of the sample handler module
// line 27 of the sample handler module
// line 28 of the sample handler module
// line 29 of the sample handler module
// line 30 of the sample handler module
// line 31 of the sample handler module
// line 32 of the sample handler module
// line 33 of the sample handler module
// line 34 of the sample handler module
// line 35 of the sample handler module
// line 36 of the sample handler module
// line 37 of the sample handler module
// line 38 of the sample handler module
// line 39 of the sample handler module
// line 40 of the sample handler module
// line 41 of the sample handler module
// line 42 of the sample handler module
// line 43 of the sample handler module
// line 44 of the sample handler module
// line 45 of the sample handler module
// line 46 of the sample handler module
// line 47 of the sample handler module
// line 48 of the sample handler module
// line 49 of the sample handler module
// line 50 of the sample handler module
// line 51 of the sample handler module
// line 52 of the sample handler module
// line 53 of the sample handler module
// line 54 of the sample handler module
// line 55 of the sample handler module
// line 56 of the sample handler module
// line 57 of the sample handler module
// line 58 of the sample handler module
// line 59 of the sample handler module
// line 60 of the sample handler module
// line 61 of the sample handler module
// line 62 of the sample handler module
// line 63 of the sample handler module
// line 64 of the sample handler module
// line 65 of the sample handler module
// line 66 of the sample handler module
// line 67 of the sample handler module
// line 68 of the sample handler module
// line 69 of the sample handler module
// line 70 of the sample handler module
// line 71 of the sample handler module
// line 72 of the sample handler module
// line 73 of the sample handler module
// line 74 of the sample handler module
// line 75 of the sample handler module
// line 76 of the sample handler module
// line 77 of the sample handler module
// line 78 of the sample handler module
// line 79 of the sample handler module
// line 80 of the sample handler module
